export default [
    {
      id: 1,
      postedOn: '2024-02-23',
      title: "Frontend Developer",
      type: "Full-time",
      location: "Remote",
      companyName: "Google",
      companyUrl: "Google.com",
      skills: ["Javascript", "React", "Node", "Tailwind", "Express", "MongoDB"],
      link: "https://google.com/careers",
      minHrRate: "$35",
      maxHrRate: "$55",
      Bop: "no", // stands for business over politics
      Experience: 'Junior Level'
    },
    {
      id: 2,
      postedOn: '2024-02-20',
      title: "Backend Developer",
      type: "Part-time",
      location: "In-person",
      companyName: "Yahoo",
      companyUrl: "Yahoo.com",
      skills: ["Angular", "Node", "TypeScript", "Express", "Firebase"],
      link: "https://yahoo.com/jobs",
      minHrRate: "$35",
      maxHrRate: "$45",
      Bop: "no",
      Experience: 'Entry Level'
    },
    {
      id: 3,
      postedOn: '2024-01-23',
      title: "iOS Developer",
      type: "Contract",
      location: "Hybrid",
      companyName: "Facebook",
      companyUrl: "https://facebook.com",
      skills: ["Flutter", "Core Data", "Swift UI", "Swift"],
      link: "https://facebook.com/careers",
      minHrRate: "$50",
      maxHrRate: "$65",
      Bop: "no",
      Experience: 'Mid Level'
    },
    {
        id: 4,
        postedOn: '2024-02-22',
        title: "Full Stack Developer",
        type: "Full-time",
        location: "Hybrid",
        companyName: "Deloitte",
        companyUrl: "https://www2.deloitte.com",
        skills: ["JavaScript", "C#", "Python", "Node", "MongoDB"],
        link: "https://www2.deloitte.com/careers",
        minHrRate: "$47",
        maxHrRate: "$57",
        Bop: "no",
        Experience: 'Junior Level'
      },
      {
        id: 5,
        postedOn: '2024-02-18',
        title: "Full Stack Developer",
        type: "Full-time",
        location: "Remote",
        companyName: "Akunna Tech Studio",
        companyUrl: "https://www.akunnatechstudio.com",
        skills: ["JavaScript", "React", "SQL", "Node", "Express","MongoDB"],
        link: "https://www.akunnatechstudio.com",
        minHrRate: "$60",
        maxHrRate: "$68",
        Bop: "yes",
        Experience: 'Senior Level'
      },
      {
        id: 6,
        postedOn: '2024-02-26',
        title: "Data Scientist",
        type: "Full-time",
        location: "Remote",
        companyName: "Google",
        companyUrl: "Google.com",
        skills: ["Python", "SQL", "Tableau", "MS Excel"],
        link: "https://google.com/careers",
        minHrRate: "$40",
        maxHrRate: "$53",
        Bop: "no",
        Experience: 'Junior Level'
      },
      {
        id: 7,
        postedOn: '2024-03-3',
        title: "Backend Developer",
        type: "Full-time",
        location: "Remote",
        companyName: "Microsoft",
        companyUrl: "https://microsoft.com",
        skills: ["JavaScript", "React", "Node", "SQL", "MongoDB"],
        link: "https://microsoft.com/careers",
        minHrRate: "$65",
        maxHrRate: "$75",
        Bop: "no",
        Experience: 'Senior Level'
      },
      {
        id: 8,
        postedOn: '2024-02-29',
        title: "Frontend Developer",
        type: "Part-time",
        location: "Hybrid",
        companyName: "Amazon",
        companyUrl: "https://amazon.com",
        skills: ["HTML", "CSS", "JavaScript", "React"],
        link: "https://amazon.com/careers",
        minHrRate: "$55",
        maxHrRate: "$67",
        Bop: "no",
        Experience: 'Mid Level'
      },
      {
        id: 9,
        postedOn: '2024-02-29',
        title: "Data Analyst",
        type: "Full-time",
        location: "In-person",
        companyName: "Facebook",
        companyUrl: "https://facebook.com",
        skills: ["SQL", "Python", "MS Excel", "Power BI", "Tableau"],
        link: "https://facebook.com/careers",
        minHrRate: "$35",
        maxHrRate: "$40",
        Bop: "no",
        Experience: 'Entry Level'
      },
      {
        id: 10,
        postedOn: '2024-02-29',
        title: "UX/UI Designer",
        type: "Part-time",
        location: "Remote",
        companyName: "Apple",
        companyUrl: "https://apple.com",
        skills: ["Adobe XD", "Sketch", "Figma", "HTML", "CSS"],
        link: "https://apple.com/careers",
        minHrRate: "$53",
        maxHrRate: "$65",
        Bop: "no",
        Experience: 'Junior Level'
      },
      {
        id: 11,
        postedOn: '2024-03-02',
        title: "Cybersecurity Analyst",
        type: "Full-time",
        location: "Hybrid",
        companyName: "Netflix",
        companyUrl: "https://netflix.com",
        skills: ["Wireshark", "Nmap", "OWASP ZAP", "Cisco ASA", "OpenSSL", "BitLocker"],
        link: "https://netflix.com/careers",
        minHrRate: "$60",
        maxHrRate: "$65",
        Bop: "no",
        Experience: 'Junior Level'
      },
      {
        id: 12,
        postedOn: '2024-02-10',
        title: "DevOps Engineer",
        type: "Contract",
        location: "Remote",
        companyName: "Tesla",
        companyUrl: "https://tesla.com",
        skills: ["Docker", "Kubernetes", "CI/CD", "AWS"],
        link: "https://tesla.com/careers",
        minHrRate: "$55",
        maxHrRate: "$58",
        Bop: "yes",
        Experience: 'Mid Level'
      },
      {
        id: 13,
        postedOn: '2024-03-04',
        title: "Machine Learning Engineer",
        type: "Full-time",
        location: "Remote",
        companyName: "IBM",
        companyUrl: "https://ibm.com",
        skills: ["Python", "PyTorch", "MXNet", "TensorFlow"],
        link: "https://ibm.com/careers",
        minHrRate: "$40",
        maxHrRate: "$50",
        Bop: "no",
        Experience: 'Entry Level'
      },
      {
        id: 14,
        postedOn: '2024-03-05',
        title: "Frontend Developer",
        type: "Full-time",
        location: "In-person",
        companyName: "Twitter",
        companyUrl: "https://twitter.com",
        skills: ["HTML", "CSS", "JavaScript", "React", "Vue"],
        link: "https://twitter.com/careers",
        minHrRate: "$52",
        maxHrRate: "$65",
        Bop: "no",
        Experience: 'Senior Level'
      },
      {
        id: 15,
        postedOn: '2024-01-04',
        title: "Backend Developer",
        type: "Full-time",
        location: "Remote",
        companyName: "LinkedIn",
        companyUrl: "https://linkedin.com",
        skills: ["Node", "Express", "MongoDB", "SQL"],
        link: "https://linkedin.com/careers",
        minHrRate: "$50",
        maxHrRate: "$65",
        Bop: "yes",
        Experience: 'Mid Level'
      },
      {
        id: 16,
        postedOn: '2024-02-04',
        title: "Cloud Engineer",
        type: "Full-time",
        location: "Hybrid",
        companyName: "Salesforce",
        companyUrl: "https://salesforce.com",
        skills: ["AWS", "Azure", "Google Cloud", "DevOps"],
        link: "https://salesforce.com/careers",
        minHrRate: "$60",
        maxHrRate: "$65",
        Bop: "yes",
        Experience: 'Mid Level'
      },
      {
        id: 17,
        postedOn:'2024-03-01',
        title: "Data Engineer",
        type: "Contract",
        location: "Remote",
        companyName: "Uber",
        companyUrl: "https://uber.com",
        skills: ["SQL", "Python", "ETL", "Snowflake", "Apache"],
        link: "https://uber.com/careers",
        minHrRate: "$50",
        maxHrRate: "$56",
        Bop: "yes",
        Experience: 'Junior Level'
      },
      {
        id: 18,
        postedOn: '2024-02-25',
        title: "Full Stack Developer",
        type: "Contract",
        location: "Remote",
        companyName: "Neptune Technologies",
        companyUrl: "https://neptunetech.com",
        skills: ["React", "Redux", "jQuery", "SQL", "AWS", "Node", "Angular", "TypeScript"],
        link: "https://neptunetech.com/careers",
        minHrRate: "$60",
        maxHrRate: "$77",
        Bop: "no",
        Experience: 'Senior Level'
      },
      {
        id: 19,
        postedOn: '2024-02-14',
        title: "Android Developer",
        type: "Full-time",
        location: "In-person",
        companyName: "Lenovo",
        companyUrl: "https://lenovo.com",
        skills: ["Java", "Kotlin", "XML", "Firebase", "UI/UX"],
        link: "https://lenovo.com/careers",
        minHrRate: "$50",
        maxHrRate: "$65",
        Bop: "yes",
        Experience: 'Mid Level'
      }                                                     
  ];
  